stages:
  - install
  - test
  - deploy

variables:
  NODE_ENV: 'development'

cache:
  paths:
    - node_modules/

before_script:
  # Install Node.js and npm
  - echo "Setting up Node.js environment..."
  - apt-get update -y
  - apt-get install -y curl
  # - curl -sL https://deb.nodesource.com/setup_14.x | bash -
  - apt-get install -y nodejs
  - node -v
  - npm install
  - npm -v


install_dependencies:
  stage: install
  script:
    - echo "Installing dependencies..."
    - npm install
  # only:
  #   - main

run_tests:
  stage: test
  script:
    - cd backend
    - echo "Running tests..."
    - npm test
  # only:
  #   - main

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
    # Add your deployment commands here
    # For example, you might use rsync or scp to copy files to a server
  # only:
  #   - main
  environment:
    name: production
    url: https://your-production-url.com
